name: Build Van Veen Website

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Install Prisma
        run: npm install prisma -g
        
      - name: Initialise Prisma database
        run: prisma generate

      - name: Run NextJS build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        run: npm run build
